language: bash
services: docker

script:
  - |
    (
      # download qemu
      curl -L https://github.com/multiarch/qemu-user-static/releases/download/v3.0.0/qemu-arm-static.tar.gz | tar zxvf - -C .
      # prepare qemu
      docker run --rm --privileged multiarch/qemu-user-static:register --reset
      # build image
      docker build -t kimdiallo/homebridge:latest --cache-from kimdiallo/homebridge .
      # test image
      docker run kimdiallo/homebridge:latest node -v
      # push image
      #  docker push kimdiallo/homebridge:latest
      fi
    )
